[package]
name = "base64"
version = "0.6.0"
authors = ["Alice Maz <alice@alicemaz.com>", "Marshall Pierce <marshall@mpierce.org>"]
description = "encodes and decodes base64 as bytes or utf8"
repository = "https://github.com/alicemaz/rust-base64"
documentation = "https://github.com/alicemaz/rust-base64/blob/master/README.md"
readme = "README.md"
keywords = ["base64", "utf8", "encode", "decode"]
categories = ["encoding"]
license = "MIT/Apache-2.0"

[features]
serde-integration = ["serde"]

[dependencies]
byteorder = "1.0.0"
safemem = "0.2.0"
serde = {version = "1.0.15", optional = true}

[dev-dependencies]
rand = "0.3.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"

[profile.bench]
# Uncomment when using `perf record`
#debug = true

